In [12]:
!pip install yahoo_fin --upgrade

Requirement already satisfied: yahoo_fin in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (0.8.9.1)
Requirement already satisfied: feedparser in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from yahoo_fin) (6.0.10)
Requirement already satisfied: pandas in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from yahoo_fin) (1.5.0)
Requirement already satisfied: requests in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from yahoo_fin) (2.28.1)
Requirement already satisfied: requests-html in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from yahoo_fin) (0.10.0)
Requirement already satisfied: sgmllib3k in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from feedparser->yahoo_fin) (1.0.0)
Requirement already satisfied: numpy>=1.21.0 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pandas->yahoo_fin) (1.23.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pandas->yahoo_fin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pandas->yahoo_fin) (2022.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests->yahoo_fin) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests->yahoo_fin) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests->yahoo_fin) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests->yahoo_fin) (2.1.1)
Requirement already satisfied: pyppeteer>=0.0.14 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests-html->yahoo_fin) (1.0.2)
Requirement already satisfied: bs4 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests-html->yahoo_fin) (0.0.1)
Requirement already satisfied: parse in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests-html->yahoo_fin) (1.19.0)
Requirement already satisfied: pyquery in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests-html->yahoo_fin) (1.4.3)
Requirement already satisfied: fake-useragent in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests-html->yahoo_fin) (1.1.1)
Requirement already satisfied: w3lib in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from requests-html->yahoo_fin) (2.1.0)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.64.1)
Requirement already satisfied: pyee<9.0.0,>=8.1.0 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (8.2.2)
Requirement already satisfied: importlib-metadata>=1.4 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (5.1.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (1.4.4)
Requirement already satisfied: websockets<11.0,>=10.0 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (10.4)
Requirement already satisfied: six>=1.5 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from python-dateutil>=2.8.1->pandas->yahoo_fin) (1.16.0)
Requirement already satisfied: beautifulsoup4 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from bs4->requests-html->yahoo_fin) (4.11.1)
Requirement already satisfied: cssselect>0.7.9 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pyquery->requests-html->yahoo_fin) (1.2.0)
Requirement already satisfied: lxml>=2.1 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from pyquery->requests-html->yahoo_fin) (4.9.1)
Requirement already satisfied: zipp>=0.5 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.11.0)
Requirement already satisfied: colorama in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from tqdm<5.0.0,>=4.42.1->pyppeteer>=0.0.14->requests-html->yahoo_fin) (0.4.6)
Requirement already satisfied: soupsieve>1.2 in c:\users\sunny\anaconda3\envs\ptsa\lib\site-packages (from beautifulsoup4->bs4->requests-html->yahoo_fin) (2.3.2.post1)

In [24]:
import yahoo_fin.stock_info as si
import pandas as pd
import re

In [58]:
aapl_earnings_hist_df = pd.DataFrame.from_dict(si.get_earnings_history("aapl"))
meta_earnings_hist_df = pd.DataFrame.from_dict(si.get_earnings_history("meta"))
goog_earnings_hist_df = pd.DataFrame.from_dict(si.get_earnings_history("goog"))
nflx_earnings_hist_df = pd.DataFrame.from_dict(si.get_earnings_history("nflx"))
amzn_earnings_hist_df = pd.DataFrame.from_dict(si.get_earnings_history("amzn"))
msft_earnings_hist_df = pd.DataFrame.from_dict(si.get_earnings_history("msft"))

In [54]:
years = ['2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']

In [59]:
aapl_earnings_10_yr_df = pd.Series(aapl_earnings_hist_df[aapl_earnings_hist_df['startdatetime'].str.contains('|'.join(years))].replace('(T(.*?)Z)','', regex=True, inplace=False)['startdatetime']).rename('aapl')
meta_earnings_10_yr_df = pd.Series(meta_earnings_hist_df[meta_earnings_hist_df['startdatetime'].str.contains('|'.join(years))].replace('(T(.*?)Z)','', regex=True, inplace=False)['startdatetime']).rename('meta')
goog_earnings_10_yr_df = pd.Series(goog_earnings_hist_df[goog_earnings_hist_df['startdatetime'].str.contains('|'.join(years))].replace('(T(.*?)Z)','', regex=True, inplace=False)['startdatetime']).rename('goog')
nflx_earnings_10_yr_df = pd.Series(nflx_earnings_hist_df[nflx_earnings_hist_df['startdatetime'].str.contains('|'.join(years))].replace('(T(.*?)Z)','', regex=True, inplace=False)['startdatetime']).rename('nflx')
amzn_earnings_10_yr_df = pd.Series(amzn_earnings_hist_df[amzn_earnings_hist_df['startdatetime'].str.contains('|'.join(years))].replace('(T(.*?)Z)','', regex=True, inplace=False)['startdatetime']).rename('amzn')
msft_earnings_10_yr_df = pd.Series(msft_earnings_hist_df[msft_earnings_hist_df['startdatetime'].str.contains('|'.join(years))].replace('(T(.*?)Z)','', regex=True, inplace=False)['startdatetime']).rename('msft')

In [60]:
earnings_10yr_df = pd.concat(
    [
        aapl_earnings_10_yr_df, 
        meta_earnings_10_yr_df, 
        goog_earnings_10_yr_df, 
        nflx_earnings_10_yr_df, 
        amzn_earnings_10_yr_df, 
        msft_earnings_10_yr_df
    ],
    axis=1
)

In [61]:
earnings_10yr_df

          aapl        meta        goog        nflx        amzn        msft
4   2022-10-27  2022-10-26  2022-07-26  2022-10-18  2022-10-27  2022-10-25
5   2022-07-28  2022-07-27  2022-04-26  2022-07-19  2022-07-28  2022-07-26
6   2022-04-28  2022-04-27  2022-02-01  2022-04-19  2022-04-28  2022-04-26
7   2022-01-27  2022-02-02  2021-10-26  2022-01-20  2022-02-03  2022-01-25
8   2021-10-28  2021-10-25  2021-07-27  2021-10-19  2021-10-28  2021-10-26
9   2021-07-27  2021-07-28  2021-04-27  2021-07-20  2021-07-29  2021-07-27
10  2021-04-28  2021-04-28  2021-02-02  2021-04-20  2021-04-29  2021-04-27
11  2021-01-27  2021-01-27  2020-10-29  2021-01-19  2021-02-02  2021-01-26
12  2020-10-29  2020-10-29  2020-07-30  2020-10-20  2020-10-29  2020-10-27
13  2020-07-30  2020-07-30  2020-04-28  2020-07-16  2020-07-30  2020-07-22
14  2020-04-30  2020-04-29  2020-02-03  2020-04-21  2020-04-30  2020-04-29
15  2020-01-28  2020-01-29  2019-10-28  2020-01-21  2020-01-30  2020-01-29
16  2019-10-30  2019-10-30  2019-07-25  2019-10-16  2019-10-24  2019-10-23
17  2019-07-30  2019-07-24  2019-04-29  2019-07-17  2019-07-25  2019-07-18
18  2019-04-30  2019-04-24  2019-02-04  2019-04-16  2019-04-25  2019-04-24
19  2019-01-29  2019-01-30  2018-10-25  2019-01-17  2019-01-31  2019-01-30
20  2018-11-01  2018-10-30  2018-07-23  2018-10-16  2018-10-25  2018-10-24
21  2018-07-31  2018-07-25  2018-04-23  2018-07-16  2018-07-26  2018-07-19
22  2018-05-01  2018-04-25  2018-02-01  2018-04-16  2018-04-26  2018-04-26
23  2018-02-01  2018-01-31  2017-10-26  2018-01-22  2018-02-01  2018-01-31
24  2017-11-02  2017-11-01  2017-07-24  2017-10-16  2017-10-26  2017-10-26
25  2017-08-01  2017-07-26  2017-04-27  2017-07-17  2017-07-27  2017-07-20
26  2017-05-02  2017-05-03  2017-01-26  2017-04-17  2017-04-27  2017-04-27
27  2017-01-31  2017-02-01  2016-10-27  2017-01-18  2017-02-02  2017-01-26
28  2016-10-25  2016-11-02  2016-07-28  2016-10-17  2016-10-27  2016-10-20
29  2016-07-26  2016-07-27  2016-04-21  2016-07-18  2016-07-28  2016-07-19
30  2016-04-26  2016-04-27  2016-02-01  2016-04-18  2016-04-28  2016-04-21
31  2016-01-26  2016-01-27  2015-10-22  2016-01-19  2016-01-28  2016-01-28
32  2015-10-27  2015-11-04  2015-07-16  2015-10-14  2015-10-22  2015-10-22
33  2015-07-21  2015-07-29  2015-04-23  2015-07-15  2015-07-23  2015-07-21
34  2015-04-27  2015-04-22  2015-01-29  2015-04-15  2015-04-23  2015-04-23
35  2015-01-27  2015-01-28  2014-10-16  2015-01-20  2015-01-29  2015-01-26
36  2014-10-20  2014-10-28         NaN  2014-10-15  2014-10-23  2014-10-23
37  2014-07-22  2014-07-23         NaN  2014-07-21  2014-07-24  2014-07-22
38  2014-04-23  2014-04-23         NaN  2014-04-21  2014-04-24  2014-04-24
39  2014-01-27  2014-01-29         NaN  2014-01-22  2014-01-30  2014-01-23
40  2013-10-28  2013-10-30         NaN  2013-10-21  2013-10-24  2013-10-24
41  2013-07-23  2013-07-24         NaN  2013-07-22  2013-07-25  2013-07-18
42  2013-04-23  2013-05-01         NaN  2013-04-22  2013-04-25  2013-04-18
43  2013-01-23  2013-01-30         NaN  2013-01-23  2013-01-29  2013-01-24
44  2012-10-25  2012-10-23         NaN  2012-10-23  2012-10-25  2012-10-18
45  2012-07-24  2012-07-26         NaN  2012-07-24  2012-07-26  2012-07-19
46  2012-04-24         NaN         NaN  2012-04-23  2012-04-26  2012-04-19
47  2012-01-24         NaN         NaN  2012-01-25  2012-01-31  2012-01-19
3          NaN         NaN  2022-10-25         NaN         NaN         NaN

In [62]:
earnings_10yr_df.to_csv('earnings_10yr_df.csv')